# Generated by Django 4.2 on 2023-11-05 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
