# Generated by Django 4.2 on 2023-11-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(default=' ', upload_to='post'),
            preserve_default=False,
        ),
    ]
